### ISSUE TITLE
rnbeads_analysis.py execution halted

### ISSUE THREAD

**Issue by FleurGaBru** [thomasvangurp/epiGBS#16]
I try to run the following code:

```
python2 epiGBS/RnBeads/rnbeads_analysis.py \
add_and_analysis \
-f ./output_DMP_Scabi/ref.fa \
-b ./output_DMP_Scabi/methylation.filtered.bed \
-sf Scabi.csv \
-tmp /tmp/ \
-s Scabi \
-g na \
-v 0.1 \
-ac na \
-mr 3 \
--context CHH
```

Before execution I installed the BSgenome package using conda:

```
conda install bioconductor-bsgenome
```

I get the following error (for the full terminal output please check the attached file:

```
Traceback (most recent call last):
  File "epiGBS/RnBeads/rnbeads_analysis.py", line 733, in <module>
    main()
  File "epiGBS/RnBeads/rnbeads_analysis.py", line 65, in main
    forge_script = forge_genome_file(description, args)
  File "epiGBS/RnBeads/rnbeads_analysis.py", line 502, in forge_genome_file
    run_subprocess(command, log_message)  # Runs the appended template script.
  File "epiGBS/RnBeads/rnbeads_analysis.py", line 134, in run_subprocess
    raise Exception('R script returned error\n%s' % stderr)
Exception: R script returned error
During startup - Warning message:
Setting LC_CTYPE failed, using "C"
Error in .copySeqFile(seqfile_name, seqs_srcdir, seqs_destdir, verbose = verbose) :
  FAILED
Calls: forgeBSgenomeDataPkg ... forgeBSgenomeDataPkg -> forgeSeqFiles -> .copySeqFile
In addition: Warning message:
In file.create(to[okay]) :
  cannot create file '/tmp//BSgenome.Scabina.NIOO.v0.1/inst/extdata/single_sequences.2bit', reason 'No such file or directory'
Execution halted
```

I can see that the output.2bit file does not exist (but output.fasta and output.bed do). Manually I can make the file by

```
/mnt/nfs/bioinfdata/home/NIOO/fleurg/projects/epiGBS_workshop/epiGBS/RnBeads/templates/faToTwoBit_linux /tmp/output.fasta /tmp/output.2bit
```

But when executing the python script the output.2bit file will disappear again.

Can you help fixing this issue?

[temp.txt](https://github.com/thomasvangurp/epiGBS/files/1450515/temp.txt)

**Comment by thomasvangurp** [comment]
I think it i because the output directory
/tmp//BSgenome.Scabina.NIOO.v0.1/inst/extdata
does not exist. Probably this directory needs to be specified... I will
look into it in more detail shortly

Met vriendelijke Groet,
Thomas van Gurp

**Comment by FleurGaBru** [comment]
/tmp/BSgenome.Scabina.NIOO.v0.1 does exist. I tried to add inst/extdata manually but that dit not solve the problem.
I hope it is just an easy thing to fix!
