### ISSUE TITLE
map_STAR.py : command not found

### ISSUE THREAD

**Issue by justinjohns** [thomasvangurp/epiGBS#7]
I think that make_reference ran successfully (although it claims a 'fatal error: unable to reallocate enough memory' near the end of the log), however I am having trouble getting mapping_variant_calling.py to run. 

I attached the make_reference.log in case this is where things got off track. 

Here is the command:
jus@jus:~/SEQ/epiGBS/mapping_varcall$ python mapping_variant_calling.py --tmpdir /tmp/ --input_dir /media/jus/seq/epiGBS_Demul_Output/denovo/ --barcodes ./barcodes.csv --threads 3 --output_dir /media/jus/seq/epiGBS_Demul_Output/output_mapping/

and the error:

Traceback (most recent call last):
  File "mapping_variant_calling.py", line 620, in <module>
    main()
  File "mapping_variant_calling.py", line 612, in main
    files = run_STAR(files,args)
[make_reference.txt](https://github.com/thomasvangurp/epiGBS/files/1143286/make_reference.txt)

  File "mapping_variant_calling.py", line 235, in run_STAR
    run_subprocess(cmd, args, log)
  File "mapping_variant_calling.py", line 108, in run_subprocess
    raise RuntimeError(stderr)
RuntimeError: /bin/bash: map_STAR.py: command not found

**Comment by justinjohns** [comment]
map_STAR.py ran after deleting the comment lines 334-337, and placing all relevant in /usr/local/bin with full permissions and changing the shebang to #! /usr/bin/python2.7. 

Additional required dependencies: pip install PyVCF \ pip install HTSeq \ sudo apt install rna-star \ sudo apt-get install tabix 

mapping_variant_calling.py ran for 12 hours, and ran into an arguments error 
"now starting:	['Run methylation calling script']
running:	methylation_calling.py  -r /media/jus/seq/refout6/consensus_cluster.renamed.fa  -m /media/jus/seq/variant5/merged.tsv.gz  -s /media/jus/seq/variant5/snp.vcf.gz  -o /media/jus/seq/variant5/methylation.bed  -heat /media/jus/seq/variant5/heatmap.igv
stderr:
usage: methylation_calling.py [-h] [-r [REFERENCE]] [-w [WATSON]] [-c [CRICK]]
                              [-m [METHYLATION_OUTPUT]] [-s [SNP_OUTPUT]]
                              [-heat [HEATMAP_OUTPUT]]
                              [-methylation_called [METHYLATION_CALLED]]
                              [-snp_called [SNP_CALLED]] [-qual [MIN_QUALITY]]
methylation_calling.py: error: unrecognized arguments: -o /media/jus/seq/variant5/methylation.bed"

I changed the -o in mapping_variant_calling.py to an -m, but now am running into this issue:

"now starting:	['Run methylation calling script']
running:	methylation_calling.py  -r /media/jus/seq/refout6/consensus_cluster.renamed.fa  -m /media/jus/seq/variant6/merged.tsv.gz  -s /media/jus/seq/variant6/snp.vcf.gz  -m /media/jus/seq/variant6/methylation.bed  -heat /media/jus/seq/variant6/heatmap.igv
stderr:
Traceback (most recent call last):
  File "/usr/local/bin/methylation_calling.py", line 889, in <module>
    main()
  File "/usr/local/bin/methylation_calling.py", line 47, in main
    files = parse_vcf(args)
  File "/usr/local/bin/methylation_calling.py", line 69, in parse_vcf
    methyl_called_file = open(args.methylation_called, 'w')
TypeError: coercing to Unicode: need string or buffer, NoneType found"
[mapping_variantcalling.txt](https://github.com/thomasvangurp/epiGBS/files/1220145/mapping_variantcalling.txt)
